#!/bin/bash
#
#######################################################################################
# StreamPi scrpit by TheOuterLinux                                                    #
#                                                                                     #
# This script is meant to be used to stream your screen to a service that supports    #
# RTMP URL's like Twitch, YouTube, Picarto, etc. However, you can also screen         #
# record to your local hard drive by using /path/to/StreamPi [output.flv]. Otherwise, #
# either do /path/to/StreamPi [rtmp://...] or change the RTMP variable below to store #
# your stream's RTMP link for you. Personally, I would leave this srcipt as is and    #
# add an alias in my .bashrc file such as:                                            #
#    alias stream_twitch="/path/to/StreamPi rtmp://..twitch..."                       #
#    alias stream_youtube="/path/to/StreamPi rtmp://..youtube..."                     #
# The title comes from the fact it was mainly tested on a Raspberry Pi 3              #
#######################################################################################
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" #Run script from any directory
#
#####[Variables - Default/Starting place]#####
RTMP="$1" #Change and use "rtmp://..." URL to store Twitch RTMP in the script otherwise, 
#..........you'll have to use "/path/to/script [rtmp://...]" each time. You can also
#..........use /path/to/script [file.flv] to screen-record to a local FLV file.

SOUNDSERVER=alsa #Defaults to ALSA because script is meant for RPi, but script down below
#.................also detects whether or not you are using something else and may change
#.................automatically to pulse.

SCALE="trunc(oh*a/2)*2:720" #Scales screen recording to 720p if screen resolution is too high.
#............................The "formula" basically prevents "divisable by two" h264 errors.
QUALITY=23 #(CRF). Don't go lower than 1 (perfect Internet) or higher than 51 (worst Internet).
#...........Changing this value can help prevent streaming errors at the expense of video quality.
THREAD_QUEUE=1024 #Needed because some systems can't record audio without it

ANTI_BOTTOM_PANEL=0 #The height of your bottom panel to block from stream; leave at "0" if you don't have one.
ANTI_TOP_PANEL=0 #The height of your top panel to block from stream; leave at "0" if you don't have one.
ANTI_LEFT_PANEL=0 #The width of your left panel to block from stream; leave at "0" if you don't have one.
ANTI_RIGHT_PANEL=0 #The width of your right panel to block from stream; leave at "0" if you don't have one.

#####[Variables - DO NOT EDIT]#####
SCREENWIDTH="$(xrandr | grep '*' | awk '{ print $1 }' | tail -n 1 | cut -d \x -f 1)" #If using ext. monitor and laptop open, get ext. monitor width
SCREENWIDTH="$(( $SCREENWIDTH - $ANTI_LEFT_PANEL - $ANTI_RIGHT_PANEL ))"
SCREENHEIGHT="$(xrandr | grep '*' | awk '{ print $1 }' | tail -n 1 | grep -o x.* | sed 's/x//g')" #If using ext. monitor and laptop open, get ext. monitor height
SCREENHEIGHT="$(( $SCREENHEIGHT - $ANTI_BOTTOM_PANEL - $ANTI_TOP_PANEL ))"

#####[Some simple audio checks - DO NOT EDIT]##### --> Still in development
#This is needed because Raspberry Pi's favor ALSA and most other systems are ok with PulseAudio.
echo "Performing audio check (ALSA vs. PulseAudio vs. JACK)..."
ALSA="$(aplay -l && echo "OK" || echo "NOK")" #Check if ALSA is running
ALSA="$(echo "$ALSA" | grep -o "OK")"
PULSE="$(pactl list && echo "OK" || echo "NOK")" #Check if PulseAudio is running
PULSE="$(echo "$PULSE" | grep -o "OK")"
SYSTEMTYPE="$(uname -m)"
if [ "$SYSTEMTYPE" = "i686" ] || [ "$SYSTEMTYPE" = "x86_64" ] && [ "$PULSE" = "OK" ] #Change sound server if not using a Pi
then
    JACKCHECK="$(ps aux | grep jackd | grep -v grep)" #If JACK is running, there will be output; otherwise, it'll be blank.
    if [ "$JACKCHECK" = "" ]
    then
        SOUNDSERVER=pulse #If JACK is NOT running, use PulseAudio
    else
        SOUNDSERVER=jack #If JACK is running, use JACK
    fi
fi

#####[Stream - DO NOT EDIT]#####
if [ "$SCREENHEIGHT" -gt 720 ] #Screen widths below 720p on a RPi do not need to be scaled
then
    ffmpeg -f $SOUNDSERVER -thread_queue_size $THREAD_QUEUE -ac 2 -i default \
    -f x11grab -video_size $SCREENWIDTH'x'$SCREENHEIGHT -i :0.0+$ANTI_LEFT_PANEL,$ANTI_TOP_PANEL -c:v libx264 -x264-params "nal-hdr=cbr" \
    -crf 23 -preset ultrafast -vf "scale=$SCALE:-1,format=yuv420p" -c:a aac -b:a 96k -ar 44100 \
    -b:v 1M -minrate 1M -maxrate 1M -bufsize 2M -f flv -movflags +faststart -profile:v baseline -level 3.0 \
    -threads 0 "$1"
else
    ffmpeg -f $SOUNDSERVER -thread_queue_size $THREAD_QUEUE -ac 2 -i default \
    -f x11grab -video_size $SCREENWIDTH'x'$SCREENHEIGHT -i :0.0+$ANTI_LEFT_PANEL,$ANTI_TOP_PANEL -c:v libx264 -x264-params "nal-hdr=cbr" \
    -crf 23 -preset ultrafast -vf "format=yuv420p" -c:a aac -b:a 96k -ar 44100 \
    -b:v 1M -minrate 1M -maxrate 1M -bufsize 2M -f flv -movflags +faststart -profile:v baseline -level 3.0 \
    -threads 0 "$1"
fi
